// <auto-generated />
namespace WatchShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Transfer_Column_DongHoThoiTrang_DongHo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Transfer_Column_DongHoThoiTrang_DongHo));
        
        string IMigrationMetadata.Id
        {
            get { return "201910211607000_Transfer_Column_DongHoThoiTrang_DongHo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
