// <auto-generated />
namespace WatchShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Set_Unique_ReadOnly_UsernameAccountManager_TenDangNhapKhachHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_Unique_ReadOnly_UsernameAccountManager_TenDangNhapKhachHang));
        
        string IMigrationMetadata.Id
        {
            get { return "201911071004066_Set_Unique_ReadOnly_UsernameAccountManager_TenDangNhapKhachHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
